apiVersion: v1
kind: {{ .Values.kind }}
metadata:
    name: {{ .Values.podname }}
spec:
    containers:
        - name: {{ .Values.containername }}
          image: {{ .Values.image }}
          volumeMounts:
            - mountPath: {{ .Values.volumes.path }}
              name: {{ .Values.volumes.name }}
    volumes:
        - name: {{ .Values.volumes.name }}
          configMap:
            name: {{ .Values.configname }}
    restartPolicy: Never

