{{- if ne .Values.createsecret false}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-helm
  labels:
    {{- include "secret.defaultlabels" . | nindent 4}}
type: Opaque
data:
  secret.value.id: {{ required "Please specify the value of secret.value" .Values.secret.creds.secretid | b64enc | quote }}
  secret.valuetwo.id: {{ required "Please specify the value of secret.valuetwo" .Values.secret.creds.secretidtwo  | b64enc | quote }}

  {{- if ne .Values.secretflag "update" }}
  k8s.secret.id: {{.Values.k8s.secret.id | b64enc | quote}}
  k8s.secret.cred: {{.Values.k8s.secret.cred | b64enc | quote}}
  {{- end}}

  {{- include "random.secret" . | nindent 2 }}
  {{- range $secret := .Values.extra.secret }}
  {{- if $secret.value }}
  {{ $secret.key }} : {{ $secret.value | b64enc | quote }}
  {{end}}
  {{ $secret.key }} : {{ randAlphaNum 10 | b64enc | quote }}
  {{end}}
{{- end}}
