apiVersion: v1
kind: Service
metadata:
{{- $ports := .Values.ports }}
{{- with .Values.service }}
    labels:
        app: {{ .labels.app }}
    name: {{ .labels.app }}-service
spec:
    type: {{ .type }}
    {{- if (or (eq .type "LoadBalancer") (eq .type "NodePort") ) }}
    externalTrafficPolicy: {{.externalTrafficPolicy}}
    {{- end }}
    ports:
        {{- range $key, $value := $ports}}
        - port: {{ $value.port }}
          protocol: {{ $value.protocol }}
          targetPort: {{ $value.targetPort }}
          name: {{ $value.name }}
          {{end}}
    selector:
        app: {{ .labels.app }}
{{- end}}